---
operator:
  telemetry:
    enabled: false
  watchNamespace: "*"
  securityContext:
    allowPrivilegeEscalation: false
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
        - ALL
