{{- $ns := include "siros-id.namespace" . -}}
---
{{ include "siros-id.certificate" (list . (dict 
  "name" "mongo-backup-client" "ou" "clients" "usages" (list "digital signature" "client auth"))) }}
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-backup-main
  namespace: {{ $ns }}
  {{- include "siros-id.labels" (list . (dict)) | nindent 2 }}
  {{- include "siros-id.annotations" (list . (dict)) | nindent 2 }}
data:
  mongoDatabases: "x"
  agePublicKeys: ""
  s3HostBase: ""
  s3AccessKey: ""
  backupPrefix: {{ $ns | quote }}

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongo-backup
  namespace: {{ $ns }}
  {{- include "siros-id.labels" (list . (dict)) | nindent 2 }}
  {{- include "siros-id.annotations" (list . (dict "reloader.stakater.com/auto" "true")) | nindent 2 }}
spec:
  schedule: "*/15 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        metadata:
          {{- include "siros-id.labels" (list . (dict
              "app.kubernetes.io/name" "mongo-backup" "mongodb-access" "true")) | nindent 10 }}
        spec:
          {{- include "siros-id.imagePullSecrets" . | nindent 10 }}
          {{- include "siros-id.podSecurityContext" (dict "runAsUser" 1000) | nindent 10 }}
          resources:
            {{- toYamlPretty .Values.resources.secretGenerator | nindent 12 }}
          volumes:
            - name: main-config
              configMap:
                name: mongo-backup-main
            - name: main-secrets
              secret:
                secretName: mongo-backup-main
            - name: mongo-cert
              secret:
                secretName: mongo-backup-client-cert
            - name: backups
              emptyDir: {}
          restartPolicy: OnFailure
          containers:
            - name: main
              image: {{ .Values.images.opsStackUtilities | quote }}
              {{- include "siros-id.imagePullPolicy" . | nindent 14 }}
              {{- include "siros-id.containerSecurityContext" (dict) | nindent 14 }}
              volumeMounts:
                - name: main-config
                  mountPath: /main-config
                  readOnly: true
                - name: main-secrets
                  mountPath: /main-secrets
                  readOnly: true
                - name: mongo-cert
                  mountPath: /mongo-cert
                  readOnly: true
                - name: backups
                  mountPath: /backups
              args:
                - /bin/bash
                - -c
                - |
                  sleep infinity

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mongo-backup
  namespace: {{ $ns }}
  {{- include "siros-id.labels" (list . (dict)) | nindent 2 }}
  {{- include "siros-id.annotations" (list . (dict)) | nindent 2 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: mongo-backup
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: mongodb-svc
      ports:
        - port: 27017
